### ISSUE TITLE
json generated by slc are not pretty formatted

### ISSUE THREAD

**Issue by sprhawk** [strongloop/strongloop#238] opened 2015-06-20 15:35 UTC
strongloop version: 4.0.5

OS: MacOSX

All json files generated by slc, including models, package.json, datasource are all compact format, meaning no new lines, all in one line.

like this:

    {"name":"loopback","version":"1.0.0","main":"server/server.js","scripts":{"pretest":"jshint."},"dependencies":{"compression":"^1.0.3","cors":"^2.5.2","errorhandler":"^1.1.1","loopback":"^2.14.0","loopback-boot":"^2.6.5","loopback-connector-mongodb":"^1.11.1","loopback-datasource-juggler":"^2.19.0","serve-favicon":"^2.0.1"},"optionalDependencies":{"loopback-explorer":"^1.1.0"},"devDependencies":{"jshint":"^2.5.6"},"repository":{"type":"","url":""},"description":"loopback"}

    {"name":"Post","plural":"posts","base":"PersistedModel","idInjection":true,"options":{"validateUpsert":true},"properties":{"timestamp":{"type":"number","required":true},"text":{"type":"string"},"photos":{"type":"array"}},"validations":[],"relations":{},"acls":[],"methods":[]}

**Comment by sam-github** [comment] 2015-06-22 03:39
Confirmed, I don't think it used to do that, maybe a change in one of the sub-deps? @ritch, ideas?

**Comment by ritch** [comment] 2015-06-22 16:47
Looking into it... this is usually because someone is calling `JSON.stringify(data)` instead of `JSON.stringify(data, null, 2)`.

@bajtos or @raymondfeng have you changed this recently? I haven't made changes to workspace in a while.

**Comment by bajtos** [comment] 2015-06-22 17:06
I am not aware of such change. I believe we use `fs-extra` to write JSON files ([source code]( https://github.com/strongloop/loopback-workspace/blob/aba8b124c95c9da5d352cea1d61c24d42a3104c9/models/config-file.js#L109)), which used to delegate that task to jsonfile ([source](https://github.com/jprichardson/node-fs-extra/blob/af1180048443b3add1f7af203ce118f30d329c15/package.json)). It seems that `jsonfile` has some regressions in `jsonfile@2.1.0`, they were fixed by https://github.com/jprichardson/node-jsonfile/commit/c2c8a2ce3a6e2fe420db1ce2fc7c3e80321e620e and released 3 days ago as `jsonfile@2.1.1`.

@sprhawk what is the version of `jsonfile` in your `strongloop` dependency tree?

**Comment by raymondfeng** [comment] 2015-06-23 19:48
@bajtos I installed strongloop@4.0.5. The problem exists even jsonfile is 2.1.2.

**Comment by raymondfeng** [comment] 2015-06-23 20:05
Here is the root cause - https://github.com/jprichardson/node-jsonfile/issues/26. I'll add a workaround first.

**Comment by raymondfeng** [comment] 2015-06-23 20:16
A workaround is released in `loopback-workspace@3.15.1`.

**Closed by raymondfeng** 2015-06-23 20:16 UTC
Labels: bug

**Comment by raymondfeng** [comment] 2015-06-23 20:17
See https://github.com/strongloop/loopback-workspace/commit/1d125e8d5731e898333e0950eacbc50e72aa7aef

**Comment by sprhawk** [comment] 2015-07-19 04:16
will this fix be available ?

    npm upgrade -g stongloop 

seems no new release

**Comment by rmg** [comment] 2015-07-20 17:29
@sprhawk IIRC, `npm upgrade -g XXX` doesn't do what one expects. You should do `npm install -g strongloop` to upgrade the strongloop package.

**Comment by raymondfeng** [comment] 2015-07-20 18:53
In some cases, I have to do the following:

```
npm uninstall -g strongloop
npm install -g strongloop
```

The following might work too:
```
npm -g cache clean
npm -g up strongloop (or npm -g install strongloop)
```

**Comment by sprhawk** [comment] 2015-07-21 02:34
thank you both @raymondfeng @rmg
