### ISSUE TITLE
Warning on installation

### ISSUE THREAD

**Issue by paulomcnally** [strongloop/strongloop#260] opened 2015-10-13 05:16 UTC
make: Leaving directory '/home/azureuser/.nvm/versions/node/v4.2.0/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-debugger/build'
    npm WARN deprecated jsonstream@1.0.3: use JSONStream instead

    [sqlite3] Success: "/home/azureuser/.nvm/versions/node/v4.2.0/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node" is installed via remote
    npm WARN deprecated showdown@0.3.1: IMPORTANT hotfix
    npm WARN deprecated react-tools@0.10.0: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated

**Comment by sam-github** [comment] 2015-10-13 17:04
Warnings are advisory. Have you experienced any issues using slc?

@jtary strong-arc could update https://www.npmjs.com/package/express-jsxtransform

@paulomcnally jsonstream is a dep of https://www.npmjs.com/package/jayson, they could probably update the dependency, though it appears to be working fine.

**Comment by natarajanmca11** [comment] 2015-10-15 15:58
I am getting the following error while install strongloop. slc arc is not working for me. 

![image](https://cloud.githubusercontent.com/assets/9244766/10519450/6e14e3de-7383-11e5-90c2-0ef76bec743a.png)

**Comment by rmg** [comment] 2015-10-15 17:46
@natarajanmca11 you need to do `npm install --global strongloop` in order for the `slc` command to be available. Without it you are just installing it in the current directory along side app dependencies.

**Comment by natarajanmca11** [comment] 2015-10-16 05:42
@rmg I tried both option. But no use. I am getting this issue after Nodejs exe upgrade to 4.2.0.

**Comment by rmg** [comment] 2015-10-16 08:30
@natarajanmca11 can you provide the contents of install2.log and npm-debug.log? The only thing your screenshot is showing are the expected error messages from optional dependencies. Are you able to install other global modules and run them?

**Comment by natarajanmca11** [comment] 2015-10-19 14:03
hi @rmg 
I shared the log file by email. 
I am getting error because of validation.vcxproj. it is more related  to MSBuild action failed. 
I have installed Visual Studio 2013 and 2015 community Edition in my local machine. 
I tried with both version as follows. 
npm install -g strongloop --msvs_version=2013
npm install -g strongloop --msvs_version=2015

please confirm strongloop supports node 4.2.0 version?

**Comment by sam-github** [comment] 2015-10-19 16:55
It does support v4.x, there are some expected errors in optional dependencies, but those do not effect its function.

**Comment by natarajanmca11** [comment] 2015-10-20 07:40
![image](https://cloud.githubusercontent.com/assets/9244766/10600967/dc5174ec-772b-11e5-8e4c-4d02bad69d94.png)

**Comment by natarajanmca11** [comment] 2015-10-21 07:12
Hi. @rmg 
Now its working fine after updating npm package from 3.3.5 to 3.3.8.
I don't know the exact root cause for this issue. Anyway it is resolved for me.
Thank you.

**Comment by rmg** [comment] 2015-10-22 22:20
@natarajanmca11 for an explanation of the problem, see npm/npm#9685, which was fixed in npm v3.3.7.

**Comment by natarajanmca11** [comment] 2015-10-23 07:58
@rmg Thank you. Now it is perfect in my local environment.

**Comment by rmg** [comment] 2015-11-22 18:40
Looks like tedeh/jayson#58 has been landed and released as jayson@1.2.2, so that takes care of our final jsonstream/JSONStream warning :-)

**Closed** 2015-11-23 15:36 UTC
