### ISSUE TITLE
passing node options!?

### ISSUE THREAD

**Issue by behrad** [strongloop/strongloop#237] opened 2015-06-16 05:15 UTC
I was unable to send `--expose-gc` and `nouse-idle-notification` to my app :(

**Comment by rmg** [comment] 2015-06-16 17:04
@behrad are you referring to `slc run`? If so, this may be a duplicate of strongloop/strong-supervisor#56.

**Comment by behrad** [comment] 2015-06-16 18:33
actually I'm abit confused about `slc run` and `slc start`!
currently using `slc run --no-profile --cluster cpu -d -l logfile.log` to run our app, however I can't see if I should switch to `slc start` or not?

so the answer should be
 
`node --harmony /usr/local/bin/sl-run run` ?
`node --harmony /usr/local/bin/sl-run start` ?

**Comment by behrad** [comment] 2015-06-16 19:07
`node --expose-gc /usr/bin/slc run` also seems to work but `node --expose-gc /usr/bin/slc start` not.

**Comment by rmg** [comment] 2015-06-16 20:14
It would not work with `slc start` because it actually deploys your app to a strong-pm instance instead of running it directly.

If this is being done on a server, you should consider http://strong-pm.io/prod/

If this is being done in development, you could continue using `slc run`.

**Comment by behrad** [comment] 2015-06-16 20:19
> If this is being done on a server, you should consider http://strong-pm.io/prod/

and how should I pass those node options in production server?

**Comment by rmg** [comment] 2015-06-16 20:30
Sorry, in my haste I focused on the `-d` in your example and forgot about the original issue. There is currently no way to pass node options to apps running under strong-pm.

**Comment by behrad** [comment] 2015-06-18 17:16
So if we are GC tuning, we should totally ignore using strong-pm currently! :(
Is there any plan to support this @rmg ?

**Comment by sam-github** [comment] 2015-07-22 00:05
We'd like to, but the priority is being balanced against lots of other outstanding feature requests.

What gc options are you providing, and what is the impact to your app?

**Comment by behrad** [comment] 2015-07-22 07:01
memory tuning and gc options for scaling...

--expose-gc
--nouse-idle-notification
--max-old-space-size

**Comment by rmg** [comment] 2017-03-13 19:57
This discussion is old. If it is still a concern, please consider opening a new issue on http://github.com/strongloop/strong-pm

**Closed by rmg** 2017-03-13 19:57 UTC
Labels: #community
