### ISSUE TITLE
npm install strongloop -g started failing today on loopback-sdk-angular-cli/bin/lb-ng ENOENT

### ISSUE THREAD

**Issue by notbrain** [strongloop/strongloop#319] opened 2016-09-06 21:05 UTC
Saw soemthing was up on our Travis CI builds but it turns out it's some issue with the strongloop install not being able to find a binary file for the `loopback-sdk-angular-cli` package. Can anyone else install strongloop right now? We've tried on (travis), local node 6.3, 6.4, npm 3.10.x.

When I try to go in and see which node_modules have been created, the strongloop folder does not exist. So not sure if it DID exist when it was trying to `chmod` the `./node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng` or if by default it deleted the strongloop folder upon failure. Which is kind of cart-before-the-horse for troubleshooting. Troubleshooting myself in the foot.

    npm ERR! Darwin 14.5.0
    npm ERR! argv "/usr/local/Cellar/node/6.4.0/bin/node" "/usr/local/bin/npm" "install" "strongloop"
    npm ERR! node v6.4.0
    npm ERR! npm  v3.10.3
    npm ERR! path /Users/notbrain/teststrongloop/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng
    npm ERR! code ENOENT
    npm ERR! errno -2
    npm ERR! syscall chmod

    npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/notbrain/teststrongloop/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng'
    npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/notbrain/teststrongloop/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng'
    npm ERR! enoent This is most likely not a problem with npm itself
    npm ERR! enoent and is related to npm not being able to find a file.
    npm ERR! enoent

**Comment by sam-github** [comment] 2016-09-06 21:06
duplicate of https://github.com/strongloop/loopback/issues/2714

**Comment by notbrain** [comment] 2016-09-06 21:07
@sam-github thanks

**Closed by sam-github** 2016-09-06 21:06 UTC

**Comment by rmg** [comment] 2016-09-07 00:59
FYI, this was resolved by #318 and released as strongloop@6.0.2
