### ISSUE TITLE
Each slc deploy commit results in new directory

### ISSUE THREAD

**Issue by superkhau** [strongloop/strongloop#287] opened 2016-01-14 19:26 UTC
See https://github.com/strongloop/loopback/issues/1956.

**Comment by superkhau** [comment] 2016-01-14 19:30
@cgole ^

**Comment by rmg** [comment] 2016-01-14 19:35
@superkhau this is a duplicate of strongloop/strong-pm#263

**Closed by rmg** 2016-01-14 19:35 UTC

**Comment by superkhau** [comment] 2016-01-14 19:42
@rmg TY
