### ISSUE TITLE
Error : "Cannot redefine property: getConnection" using slc run to start a server

### ISSUE THREAD

**Issue by amerishk** [strongloop/strongloop#330] opened 2016-10-11 14:20 UTC
Hello,

When using oracledb (node-oracle) module to establish a connection in a SLC Project, we are getting "error: uncaughtException: Cannot redefine property: getConnection ". This is happening whenever we use "SLC RUN" to start the node server. On the other than, when we use "NODE ." everything works. We asked the same issue in node-oracledb (git) (link https://github.com/oracle/node-oracledb/issues/505) but got redirected to Strongloop team. 

The issue is with the getConnection property of Oracledb instance present in Oracledb.js. This attribute is writable as true. If we add _"configurable: true"_ to the getConnection property all works fine. 

Can you please look into this issue as the earliest?

Below is the sample code: 

var oracledb = require('oracledb'); // while start-up at this line we are getting the ERROR.

oracledb.getConnection(
{
user : "test",
password : "test",
connectString : "localhost/XE"
},
function(err, connection)
{
if (err) { console.error(err.message); return; }

connection.execute(
  "SELECT department_id, department_name " +
    "FROM departments " +
    "WHERE manager_id < :id",
  [110],  // bind value for :id
  function(err, result)
  {
    if (err) { console.error(err.message); return; }
    console.log(result.rows);
  });
});
### Expected result

Server should have started successfully without any issues.
### Actual result (if bug)

On server start-up using SLC RUN Command, we are getting below error (error log):

_error: uncaughtException: Cannot redefine property: getConnection_ date=Mon Oct 10 2016 21:46:43 GMT+0530 (India Standard Time), pid=11016, uid=null, gid=null, cwd=D:\Project, execPath=C:\Program Files\nodejs\node.exe, version=v4.2.3, argv=[C:\Program Files\nodejs\node.exe, server\server.js], rss=99450880, heapTotal=74440704, heapUsed=52147416, loadavg=[0, 0, 0], uptime=48725.2610621, trace=[column=null, file=null, function=Function.defineProperty, line=null, method=defineProperty, native=true, column=10, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js, function=install, line=259, method=null, native=false, column=38, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js, function=null, line=59, method=null, native=false, column=32, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js, function=null, line=133, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js, function=each, line=133, method=null, native=false, column=3, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js, function=around, line=55, method=null, native=false, column=40, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js, function=Object.after, line=19, method=after, native=false, column=9, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\probes\oracledb.js, function=oracleBase, line=20, method=null, native=false, column=10, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\probes\oracledb.js, function=oracledb, line=15, method=null, native=false, column=50, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\agent.js, function=Module.module.**proto**.require, line=188, method=module.**proto**.require, native=false, column=17, file=module.js, function=require, line=385, method=null, native=false, column=16, file=D:\Project\common\adapters\adapterv10\adapterv10.js, function=, line=23, method=null, native=false, column=26, file=module.js, function=Module._compile, line=435, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=442, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false], stack=[TypeError: Cannot redefine property: getConnection,     at Function.defineProperty (native),     at install (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js:259:10),     at C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js:59:38,     at C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js:133:32,     at Array.forEach (native),     at each (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js:133:8),     at around (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js:55:3),     at Object.after (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js:19:40),     at oracleBase (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\probes\oracledb.js:20:9),     at oracledb (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\probes\oracledb.js:15:10),     at Module.module.__proto__.require (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\agent.js:188:50),     at require (module.js:385:17),     at Object.<anonymous> (D:\Project\common\adapters\adapterv10\adapterv10.js:23:16),     at Module._compile (module.js:435:26),     at Object.Module._extensions..js (module.js:442:10),     at Module.load (module.js:356:32)]
### Additional information (Node.js version, LoopBack version, etc)

Node JS Version - 0.10.40 and 4.2.3 ( we tried on both versions)
loopback version - 5.0.1 and 6.0.1 (we tried on both versions)
Node-oracledb / Oracledb Versoin - 1.11
Oracle 11g XE

**Comment by raymondfeng** [comment] 2017-01-26 16:17
Close it as a duplicate of https://github.com/strongloop/loopback/issues/2873

**Closed by raymondfeng** 2017-01-26 16:17 UTC
